const state = { passages:{}, difficulty:'easy', mode:'timed', text:'', typed:'', errors:0, started:false, finished:false, seconds:60, interval:null, startTime:null };
    const $ = id => document.getElementById(id);
    const el = { passage:$('passage'), input:$('typing-input'), overlay:$('start-overlay'), restartRow:$('restart-row'), wpm:$('wpm'), accuracy:$('accuracy'), time:$('time'), results:$('results'), test:$('test-area'), best:$('personal-best') };
    const formatTime = seconds => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2,'0')}`;
    const calc = () => { const elapsed = state.mode === 'timed' ? 60 - state.seconds : Math.max(1, Math.floor((Date.now()-state.startTime)/1000)); const correct = [...state.typed].filter((c,i) => c === state.text[i]).length; const activeErrors = [...state.typed].filter((c,i) => c !== state.text[i]).length; const attempts = state.typed.length + Math.max(0, state.errors - activeErrors); return { correct, elapsed, accuracy: attempts ? Math.round(correct / attempts * 100) : 100, wpm: Math.round((correct / 5) / (elapsed / 60)) || 0 }; };
    function updateStats() { const v = calc(); el.wpm.textContent = v.wpm; el.accuracy.textContent = `${v.accuracy}%`; el.time.textContent = formatTime(state.mode === 'timed' ? state.seconds : v.elapsed); }
    function renderPassage() { el.passage.innerHTML = [...state.text].map((char,i) => { let cls='char'; if(i < state.typed.length) cls += state.typed[i] === char ? ' correct' : ' incorrect'; else if(i === state.typed.length && state.started) cls += ' current'; return `<span class="${cls}">${char === ' ' ? '&nbsp;' : char}</span>`; }).join(''); }
    function choosePassage() { const pool = state.passages[state.difficulty] || []; state.text = pool[Math.floor(Math.random()*pool.length)]?.text || 'Loading a new typing passage failed. Please refresh the page.'; state.typed=''; state.errors=0; state.seconds=60; state.finished=false; state.started=false; clearInterval(state.interval); el.input.value=''; el.overlay.classList.remove('hidden'); el.restartRow.classList.remove('visible'); el.passage.classList.add('is-idle'); el.test.hidden=false; el.results.classList.remove('visible'); updateStats(); renderPassage(); }
    function start() { if(state.started || state.finished) return; state.started=true; state.startTime=Date.now(); el.overlay.classList.add('hidden'); el.restartRow.classList.add('visible'); el.passage.classList.remove('is-idle'); el.input.focus(); renderPassage(); if(state.mode === 'timed') state.interval=setInterval(() => { state.seconds--; updateStats(); if(state.seconds <= 0) finish(); },1000); else state.interval=setInterval(updateStats,500); }
    function finish() { if(state.finished) return; state.finished=true; clearInterval(state.interval); el.input.blur(); const v=calc(); updateStats(); const oldBest=Number(localStorage.getItem('typing-best') || 0); const first=!oldBest, newBest=v.wpm > oldBest; if(newBest || first) localStorage.setItem('typing-best', String(v.wpm)); updateBest(); $('result-wpm').textContent=v.wpm; $('result-accuracy').textContent=`${v.accuracy}%`; $('result-characters').textContent=`${v.correct}/${state.errors}`; $('result-title').textContent=first ? 'Baseline Established!' : newBest ? 'High Score Smashed!' : 'Test Complete!'; $('result-message').textContent=first ? 'Your personal best is now set. The next run is yours to beat.' : newBest ? 'A new personal best. That was seriously quick!' : 'Solid run. Keep pushing to beat your high score.'; el.test.hidden=true; el.results.classList.add('visible'); }
    function updateBest() { const best=localStorage.getItem('typing-best'); el.best.textContent=best ? `${best} WPM` : 'â€”'; }
    el.input.addEventListener('input', e => { if(!state.started) start(); const value=e.target.value; if(value.length > state.typed.length) { const index=state.typed.length; if(value[index] !== state.text[index]) state.errors++; } state.typed=value.slice(0,state.text.length); e.target.value=state.typed; renderPassage(); updateStats(); if(state.typed === state.text) finish(); });
    $('start-button').addEventListener('click', start); el.passage.addEventListener('click', start); $('again').addEventListener('click', choosePassage); $('restart').addEventListener('click', choosePassage);
    document.querySelectorAll('[data-difficulty]').forEach(button => button.addEventListener('click', () => { if(state.started) return; state.difficulty=button.dataset.difficulty; document.querySelectorAll('[data-difficulty]').forEach(b=>b.classList.toggle('active',b===button)); choosePassage(); }));
    document.querySelectorAll('[data-mode]').forEach(button => button.addEventListener('click', () => { if(state.started) return; state.mode=button.dataset.mode; document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===button)); choosePassage(); }));
    fetch('./data.json').then(r=>r.json()).then(data => { state.passages=data; choosePassage(); }).catch(() => { state.passages={easy:[{text:'Practice makes progress. Keep your eyes on the text and type with a steady rhythm.'}]}; choosePassage(); }); updateBest();
